### PR TITLE
Update 2024-02-27-noskov24a.md, Panic to Panov

### PR DESCRIPTION
**Pull request by TulaShlyosberg**
There is a typo in the name of one author. There should be Panov instead of Panic

### CODE REVIEW

**Review by lawrennd — CHANGES_REQUESTED** [review]
Thanks, this also needs fixing in the bibtex author field.

**Review by lawrennd — CHANGES_REQUESTED** [review]
The field bibtex_author is in the same file you edited originally. The bib file shouldn't be changed (that's just there for reference).

**Comment by TulaShlyosberg** [comment]
Thank you for help!

**Review by lawrennd — APPROVED** [review]
Perfect!

**Pull request merged**
